# Generated by Django 3.1.3 on 2021-03-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('adharno', models.BigIntegerField(unique=True)),
                ('phoneno', models.BigIntegerField(unique=True)),
                ('role', models.TextField()),
                ('sallery', models.FloatField()),
                ('dob', models.DateField()),
                ('education', models.TextField(blank=True)),
                ('workexperience', models.IntegerField()),
                ('recuritmentdate', models.DateField()),
                ('medicalhistory', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='sallery_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.IntegerField()),
                ('Absent_days', models.IntegerField()),
                ('Working_days', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('salary', models.FloatField()),
                ('overtimr_hrs', models.FloatField()),
                ('overtime_salary', models.FloatField()),
                ('total_sallery', models.FloatField()),
                ('advance_sallery', models.FloatField()),
                ('balance_sallary', models.FloatField()),
                ('date_of_payment', models.DateField()),
                ('payment_mode', models.CharField(max_length=10)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employeeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendenceInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('remark', models.CharField(max_length=2, null=True)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employeeinfo')),
            ],
        ),
    ]
