# Generated by Django 3.1.3 on 2021-03-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyattendenceinfor',
            old_name='Emp_id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='sallery_report',
            old_name='Emp_id',
            new_name='emp_id',
        ),
    ]
